# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Remove to go root
      run: cd /home/runner/go
    - name: Create bin
      run: mkdir bin
    - name: Create src
      run: mkdir src
    - name: go into src
      run: cd src
    # - name: Remove project
    #   run: cp -r /home/runner/work/treasurenet /home/runner/go/src/
    # - name: Go to project root
    #   run: cd /home/runner/go/src
    - name: look
      run: ls
    # - name: Go to project root
    #   run: cd /home/runner/go/src/treasurenet
    # - name: Enable Go modules
    #   run: go env -w GO111MODULE=on
    # - name: Auto Init
    #   run: init-gravity.sh
    # - name: Start node
    #   run: $BIN start --pruning=nothing --log_level $LOGLEVEL --json-rpc.api eth,txpool,personal,net,debug,web3,miner --trace --json-rpc.address 0.0.0.0:8555

    
